version: '3.8'

services:
        janus-gateway:
                image: 'canyan/janus-gateway:latest'
                command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
                network_mode: host
                #ports:
                #- "8188:8188"
                #- "8088:8088"
                #- "8069:8089"
                #- "8869:8889"
                #- "8001:8001"
                #- "7088:7088"
                #- "7089:7089"
                #- "5000-6000:5000-6000/udp"
                volumes:
                        - ./janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg
                        - ./janus/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg
                          #- ./janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg
                restart: always
                profiles:
                        - donotstart
                          
        signaling:
                build:
                        context: ./signaling
                        #command: >
                        #bash -c "while true; do nc -lp 9999; done"
                expose:
                        - 9999
                network_mode: host
                          #networks:
                          #- internal_net

        nginx:
                image: umputun/nginx-le:latest
                hostname: nginx
                restart: always
                container_name: nginx

                logging:
                        driver: json-file
                        options:
                                max-size: "10m"
                                max-file: "5"

                volumes:
                        - ./ssl:/etc/nginx/ssl
                        - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx_conf/service.conf:/etc/nginx/service.conf
                        - ./single_frontend:/usr/share/nginx/html
                          # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
                          # - ./etc/stream-example-2.conf:/etc/nginx/stream2.conf # more streams, should be stream*.conf
                          # - ./etc/conf.d:/etc/nginx/conf.d-le # configuration folder, all files from it will be added
                          # - ./etc/stream.conf:/etc/nginx/stream.conf.d-le # streams configuration folder, all files from it will be added
                          #ports:
                          #- "80:80"
                          #- "443:443"
                          #ports:
                          #- target: 80
                          #mode: host
                          #protocol: tcp
                          #published: 80
                          #- target: 443
                          #mode: host
                          #protocol: tcp
                          #published: 443
                          #networks:
                          #- internal_net
                #profiles:
                #        - donotstart
                network_mode: host

                environment:
                        - TZ=Europe/Moscow
                        - LETSENCRYPT=true
                        - LE_EMAIL=terenty.rezman@gmail.com
                        - LE_FQDN=2089517-cn34567.twc1.net,turn.2089517-cn34567.twc1.net,stun.2089517-cn34567.twc1.net
        coturn:
                image: coturn/coturn:latest
                container_name: coturn
                restart: always
                network_mode: host
                volumes:
                        - ./coturn/turnserver.conf:/etc/turnserver.conf:ro
                        - ./ssl_coturn/le-key.pem:/etc/ssl/privkey.pem:ro
                        - ./ssl_coturn/le-crt.pem:/etc/ssl/certs/cert.pem:ro
                depends_on: 
                        - nginx
        #ports:
                #- 3478:3478
                #- 3478:3478/udp
                #- 5349:5349
                #- 5349:5349/udp
                #- "49152-65535:49152-65535/udp"
                          #volumes:
                          #- ./nginx_conf/ssl:/etc/nginx/ssl
networks:  
  internal_net:
