version: "3.8"

services:
  control:
    build: .
    command: python3 control_server.py
    volumes:
      - .:/code
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0 
    ports:
      - 0.0.0.0:80:80
    restart: always
